services:
  redis:
    image: redis:alpine

    ports:
      - '6379:6379'

  app:
    build: .

    stop_signal: SIGINT

    ports:
      - '5000:5000'

    environment:
      - APP_PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379

    depends_on:
      - redis
